site_name: Mi super proyecto Youtube
site_url: http://lgarciavelazquez.github.io/myMkdocs/
site_dir: /docs
docs_dir: /pages
nav:
  - Home: index.md
  - Varias cosas: varios.md
  - Otras: otros.md

# theme: readthedocs
theme: terminal

